[build]
  publish = ".next"
  command = "npm run build"

[functions]
  # Maximum timeout for Netlify Functions (15 seconds)
  timeout = 15

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  # Environment variables for async operations
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Async configuration
  ASYNC_MODE = "true"
  POLLING_TIMEOUT = "180000"  # 3 minutes
  WEBHOOK_TIMEOUT = "12000"   # 12 seconds

[dev]
  framework = "next"
  command = "npm run dev"
  targetPort = 3000

# Headers for better caching and security
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"